// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1SSGBbrb55vD1FZdp3km0O6A3PVOnhM',
    appId: '1:865362136741:web:632a73cbd45c4fb603474c',
    messagingSenderId: '865362136741',
    projectId: 'winnerspin-fc03f',
    authDomain: 'winnerspin-fc03f.firebaseapp.com',
    storageBucket: 'winnerspin-fc03f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHFzmUvbJMlIxrZNf0tJG7817FCjMurbA',
    appId: '1:865362136741:android:05ae064acce56d6d03474c',
    messagingSenderId: '865362136741',
    projectId: 'winnerspin-fc03f',
    storageBucket: 'winnerspin-fc03f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkY0zfAb3rSFi2QwiIDW1gBwISe5jY0GU',
    appId: '1:865362136741:ios:d4b197d001e8a57703474c',
    messagingSenderId: '865362136741',
    projectId: 'winnerspin-fc03f',
    storageBucket: 'winnerspin-fc03f.firebasestorage.app',
    iosBundleId: 'com.example.winnerSpin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkY0zfAb3rSFi2QwiIDW1gBwISe5jY0GU',
    appId: '1:865362136741:ios:d4b197d001e8a57703474c',
    messagingSenderId: '865362136741',
    projectId: 'winnerspin-fc03f',
    storageBucket: 'winnerspin-fc03f.firebasestorage.app',
    iosBundleId: 'com.example.winnerSpin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1SSGBbrb55vD1FZdp3km0O6A3PVOnhM',
    appId: '1:865362136741:web:023cb79c2b483f2103474c',
    messagingSenderId: '865362136741',
    projectId: 'winnerspin-fc03f',
    authDomain: 'winnerspin-fc03f.firebaseapp.com',
    storageBucket: 'winnerspin-fc03f.firebasestorage.app',
  );
}